server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

  datasource:
    url: jdbc:mysql://localhost:3306/BookingDB
    username: root
    password:
  application:
    name: booking-microservice

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}